version: "3.9"
services:
  db:
    image: mysql:8.0
    volumes:
      - "./sql-scripts:/docker-entrypoint-initdb.d"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
